# This is a basic workflow to help you get started with Actions

name: Nuget Publish for Master/Main Branch

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #Setup .Net to support .Net versions (.Net Core 3.1, .Net 6.0, etc.)
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: | 
            6.0.x
            
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Executing Main Branch commit Workflow!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
      - name: "Publish NuGet: LazyCacheHelpers"
        #BBernard - 05/17/2022
        #Per the Thread here, I kept getting "error: File does not exist (1)." but this other Fork resolves it
        #   as noted by the 11 Stars on it (vs many other random forks).
        #   https://github.com/brandedoutcast/publish-nuget/issues/76#issuecomment-1118344860
        #uses: brandedoutcast/publish-nuget@v2.5.5
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: LazyCacheHelpers/LazyCacheHelpers.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: "Publish NuGet: LazyCacheHelpers.ConfigurationManager"
        #BBernard - 05/17/2022
        #Per the Thread here, I kept getting "error: File does not exist (1)." but this other Fork resolves it
        #   as noted by the 11 Stars on it (vs many other random forks).
        #   https://github.com/brandedoutcast/publish-nuget/issues/76#issuecomment-1118344860
        #uses: brandedoutcast/publish-nuget@v2.5.5
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: LazyCacheHelpers.ConfigurationManager/LazyCacheHelpers.ConfigurationManager.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
